### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by shrewmus** [epm-dev-priporov/idea-notes#40]
Please update to allow new IDE version

**Comment by epm-dev-priporov** [comment]
Thank you for the report. New version is uploaded and will be available after JB review. Usually it takse about 1-3 business days.

**Comment by shrewmus** [comment]
Thank you. It works.

Just deprecated note appears (not the critical for now I assumed)

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'dev.priporov.ideanotes.toolbar.NoteToolbarActionButton' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: dev.priporov.idea.notes]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```
