### ISSUE TITLE
Exception in NotesTree 1.5.1 - what does it mean and how to fix?

### ISSUE THREAD

**Issue by squeezer44** [epm-dev-priporov/idea-notes#44]
Hi,

after starting my PyCharm Professional IDE

PyCharm 2024.2.2 (Professional Edition)
Build #PY-242.22855.92, built on September 19, 2024
Runtime version: 21.0.3+13-b509.15 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
Memory: 10000M
Cores: 12

I received this error:

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'dev.priporov.ideanotes.action.common.CopyFromIdeProjectStructureAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: dev.priporov.idea.notes]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```

What ddoes it mean and how to fix it?
Thx

**Comment by epm-dev-priporov** [comment]
@squeezer44 Hello and thank you for the report, 
This is minor issue which only highlights that **CopyFromIdeProjectStructureAction** class should override this method. This is actually already fixed in 1.5.2 and doesn't affect somehow the work of the plugin or IDE, beside the warning message. I didn't upload 1.5.2 version because it has only one fix of  this and nothing more issue and in my opiniot it's not enought to publish it. But I will publish as 1.5.1-1 to this message doesn't distract users.

**Comment by squeezer44** [comment]
@epm-dev-priporov 
Thx for your answer.
